### ISSUE TITLE
Event after scan is completed

### ISSUE THREAD

**Issue by mitesh-shah** [Zebra/ZebraIonicDemo#9]
@darryncampbell I am having Zebra device and I am scanning using hardware detector.

I want to get an event once the scanning is finished, so that I can perform rest of the activities.

Is there any event that we get once we get the data?

**Comment by darryncampbell** [comment]
When this sample app receives the Intent from DataWedge containing the scan data (https://github.com/Zebra/ZebraIonicDemo/blob/master/src/providers/barcode/barcode.ts#L71) it indicates that the scan is completed, is that what you mean?  Or are you doing something more complicated?

**Comment by mitesh-shah** [comment]
Actually, I am developing an app for a retail store in angular + ionic and using Zebra device.

On one of screen, I need to scan the barcode using hardware barcode detector. As soon as, barcode gets placed in the input field, I need to call search function.

Without writing any code (for barcode scanning), I am able to read the barcode, but to call a search function, I have written all the code mentioned in this demo but had no luck.

**Comment by darryncampbell** [comment]
So, are you using the Keystroke output plugin of DataWedge to get the barcode data into your input field?  (https://techdocs.zebra.com/datawedge/7-4/guide/output/keystroke/)  If so, you probably want to use the Intent output plugin, as used by this demo, since then you will know when the scan data has been received.

**Comment by mitesh-shah** [comment]
Honestly, not sure which plugin I am using.

The device I have is, Zebra-TC52. When I want to scan a barcode, I open my app -> go to desired screen -> point the phone towards barcode -> click the hardware black button on phone's left/right hand side -> Phone then start a red light detector, scans the barcode and place the string in my app's input field.

**Comment by darryncampbell** [comment]
In order to know when the scan is complete it will be easiest to use the Intent plugin - please take a look at the Setup instructions in the ReadMe of this repository or for more information see https://techdocs.zebra.com/datawedge/.  This sample app uses the Intent plugin but it sounds like you have it set up to use the keystroke plugin, in which case it is difficult to know that the scan is complete in the text field.

**Comment by mitesh-shah** [comment]
Ok. Thank you.
